### ISSUE TITLE
Support for other output.

### ISSUE THREAD

**Issue by cheako** [ac000/libctemplate#1]
I have need to send output over SSL and I'd imagine there are other reasons to want the output not sent to a fd.  I think I can make the necessary changes, I just wonder which branch I should base my changes from?

My thoughts are to implement a lower level interface alongside TMPL_write() where there would be an opportunity to define callbacks for the output of an ASCII string and the raising of an error enum with a function to resolve the enumeration to a string.

**Comment by ac000** [comment]
Firstly let me apologise for the late reply, but I've only just noticed this!.

Secondly let me make it clear that I am not the author of libctemplate.

I have myself moved away from using libctemplate and switched to libflate[0], again, I am not the author of that either,

The 'otl' branch here was to make libctemplate work with FastCGI[1]

Now as for your suggestion. To be honest my feeling is that a templating library shouldn't really concern itself with such things.

I'm not really doing anything with these nowadays, but if I was, I would change libctemplate to just return the processed HTML in a memory buffer (like libflate's flatePage()), then you can do whatever you want with it, write it to a file, send it over the network etc...
 
Andrew

[0] - https://github.com/ac000/libflate
[1] - https://web.archive.org/web/20160119141816/http://www.fastcgi.com/drupal/node/6?q=node%2F22
