### ISSUE TITLE
Is libctemplate thread-safe?

### ISSUE THREAD

**Issue by coterobarros** [ac000/libctemplate#2]
Sorry, this is not a real issue, just a question: is libctemplate a thread-safe library?
Thanks in advance.

**Comment by ac000** [comment]
Hi,

I believe it is _mostly_ thread safe. There isn't any global state and there are no non-const static local variables. The only fly in the ointment is possibly the use of ```va_arg(3)``` which is listed in the Linux man page under ```ATTRIBUTES``` as
```
       │va_arg()                            │ Thread safety │ MT-Safe race:ap │
```
which means there could be a potential issue with the ap parameter.

**Comment by coterobarros** [comment]
Great! Thank you for your time
